import Token from "@host/components/Token";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Host</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Host</h1>
          <Token />
        </div>
      </main>
    </>
  );
}
